### ISSUE TITLE
Marshaller throws a warning

### ISSUE THREAD

**Issue by steefaan** [UseMuffin/Webservice#10]
@Marlinc Please correct me if I'm wrong but I think this condition will throw a warning almost everytime, when an empty string will be marshalled: https://github.com/UseMuffin/Webservice/blob/master/src/Marshaller.php#L71

It's probably a copy/paste issue from Cake's ORM but this will return usually a string:  https://github.com/UseMuffin/Webservice/blob/master/src/Marshaller.php#L53

On Cake's ORM it will always return an array, why it works there: https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/Table.php#L505

**Comment by steefaan** [comment]
An array typcast could help here: https://github.com/UseMuffin/Webservice/blob/master/src/Marshaller.php#L53

**Comment by Marlinc** [comment]
Would it make sense to return a array from the `Endpoint` class just like `Table` to be consistent with the framework?

**Comment by steefaan** [comment]
No I don't think so probably it's better to change the condition itself to a non-array solution. Don't know in which cases `primaryKey()` is an array.

**Comment by Marlinc** [comment]
This is in general used by databases to allow composite primary keys (multiple columns combined as primary key). That's why the CakePHP ORM returns a array in the `primaryKey()` method.

**Comment by steefaan** [comment]
Ok in endpoint context not really necessary so yes, returning a string instead and change the condition should be fine.

**Comment by Marlinc** [comment]
I've opened a PR for this: #11.

**Comment by Marlinc** [comment]
@steefaan you were right with the array typecast, I'm sorry. The CakePHP `Table` also supports arrays and strings so they use a array cast as well. I've opened a new PR for this: #14.
