### ISSUE TITLE
Missing Datasource Configuration

### ISSUE THREAD

**Issue by assisjeferson** [UseMuffin/Webservice#20]
I'm trying use this lib, but always return  _Missing Datasource Configuration_

**Comment by Marlinc** [comment]
Can you give an example of your current setup?

**Comment by assisjeferson** [comment]
I'm using the readme example

When I call `$this->loadModel('Articles', 'Endpoint');`, return `MissingDatasourceConfigException`

**Comment by assisjeferson** [comment]
I found the error.

In `EndpointRegistry.php` line 72, always try get connection manager `app`, I found this code and change the array key for app and the error disappear.

```php
'Webservices' => [
        'app' => [
            'className' => 'Muffin\Webservice\Connection',
            'service' => 'App\Webservice\Driver\Articles',
            ],
        ]
```
