### ISSUE TITLE
Unknown repository type error

### ISSUE THREAD

**Issue by panda1111** [UseMuffin/Webservice#25]
I have clear install of CakePHP (latest).

After I've followed all of the steps provided in the "Usage" section of this plugin I'm stuck on the _Unknown repository type "Endpoint". Make sure you register a type before trying to use it._ error.

Not sure how to register this type. I've tried

public function beforeFilter(Event $event)
    {
        $this->modelFactory(
            'Endpoint',
            ['Endpoint', 'factory']
        );
        $this->loadModel('Articles', 'Endpoint');
    }

but got Argument 2 passed to Cake\Controller\Controller::modelFactory() must be callable, array given error.

**Comment by agaleski** [comment]
Possible quick fix.

try using this:
`$this->modelFactory('Endpoint', ['Muffin\Webservice\Model\EndpointRegistry', 'factory']);`

I do not have enough details to check or try it. Hope this helps.

**Comment by panda1111** [comment]
Thanks for the reply!
Unfortunately it shows the same error: "Argument 2 passed to Cake\Controller\Controller::modelFactory() must be callable, array given"
May be I did something wrong installing this package.

Please tell me what details you need. I can put the whole test project on the GitHub if it can help.

**Comment by agaleski** [comment]
Which CakePhp Version do you use?
Have you added the plugin via `composer require` ?
Does you `bootstrap.php` contain this line:
`Plugin::load('Muffin/Webservice', ['bootstrap' => true]);` 
?

**Comment by panda1111** [comment]
1. CakePHP version is 3.3.4
2. Yes. I have the plugin added via composer require
3. Yes

**Comment by agaleski** [comment]
Use this 
```
public function beforeFilter(Event $event)
{
    $this->modelFactory('Endpoint', ['Muffin\Webservice\Model\EndpointRegistry', 'get']);
    $this->loadModel('Articles', 'Endpoint');
}
```

I have tested it at a fresh installation of CakePhp 3.3.4
You have to add the line `$this->modelFactory('Endpoint', ['Muffin\Webservice\Model\EndpointRegistry', 'get']);` or you run into the initial described error in this issue.

May be the README.md should be updated.

**Comment by panda1111** [comment]
Thank you! Problem solved.

**Comment by davidyell** [comment]
Just this this also myself.
