### ISSUE TITLE
BUILD_VALIDATOR_EVENT class constant

### ISSUE THREAD

**Issue by andrej-griniuk** [UseMuffin/Webservice#47]
In CakePHP 3.5 classes using `ValidatorAwareTrait` must have `BUILD_VALIDATOR_EVENT` constant defined. In this case `Muffin\Webservice\Model\Endpoint` class. Currently causing "Undefined class constant 'BUILD_VALIDATOR_EVENT'" exception.

**Comment by ADmad** [comment]
Duplicate of #46.
