### ISSUE TITLE
Trouble with Usage Example

### ISSUE THREAD

**Issue by nifa-dev** [UseMuffin/Webservice#50]
I'm working through the usage example in the readme and have stumbled across an issue that's probably simple, but I'm stuck on.

I'm struggling with the example Webservice.

```
<?php

namespace App\Webservice;

use Cake\Network\Http\Client;
use Muffin\Webservice\Query;
use Muffin\Webservice\Webservice\Webservice;

class ArticlesWebservice extends Webservice
{

    /**
     * {@inheritDoc}
     */
    protected function _executeReadQuery(Query $query, array $options = [])
    {
        $response = $this->driver()->client()->get('/articles.json');

        if (!$response->isOk()) {
            return false;
        }

        $resources = $this->_transformResults($query->endpoint(), $response->json['articles']);

        return new ResultSet($resources, count($resources));
    }
}
```
Running this code I'm seeing an "Class 'App\Webservice\ResultSet' not found" error.

What class/file/source does `new ResultSet($resources, count($resources));` come from?

I've looked through the included classes and can't seem to find it.  So, I assumed maybe the example just forgot `use Cake\ORM\ResultSet`.  Looking at the spec for `Cake\ORM\ResultSet` the input variables are a `Cake\ORM\Query` and `Cake\Database\StatementInterface`.  The variables passed to `ResultSet` in the example are not those types.

What am I missing here?

Thanks!

**Comment by ADmad** [comment]
The e.g. is missing `use Muffin\Webservice\ResultSet` above the class.
