### ISSUE TITLE
Error when i use cake 3.6 with debugkit

### ISSUE THREAD

**Issue by makamo** [UseMuffin/Webservice#70]
#In the latest version of debugkit, they use setLogger() instead of logger().
https://github.com/cakephp/debug_kit/blame/0d70858a4f01d24f17514ee2f9dc0f0c92f4f3e8/src/Panel/SqlLogPanel.php#L67
So it creates an exception because the returned logger is not an instance of the Psr\Log\LoggerInterface

This could be the solution
https://github.com/UseMuffin/Webservice/commit/2882e913afd615bf6604b43df5d97e676d3784ae

ref : https://github.com/cakephp/debug_kit/issues/624

**Comment by davidyell** [comment]
I've managed to sidestep this issue like this

```php
    public function setLogger($logger)
    {
        $this->logger = new NullLogger();
    }
```

**Comment by Nic0tiN** [comment]
I have the same issue but can't use @davidyell's workaround.

**Comment by ADmad** [comment]
@Nic0tiN Make some noise on the debugkit issue linked in first comment. This issue *should* be fixed in debukit / core and people shouldn't have to resort to workarounds in app/plugin code.

**Comment by Asgraf** [comment]
In cake 3.7 there is similar problem:
When DebugKit plugin is enabled exception `Muffin\Webservice\Exception\UnimplementedWebserviceMethodException` is thrown with following the error message:
`Webservice [servicename] does not implement isQueryLoggingEnabled `
