### ISSUE TITLE
Complete testing for 2.0 release

### ISSUE THREAD

**Issue by davidyell** [UseMuffin/Webservice#74]
I am creating a ticket for myself to polish off the final few bits that might be needed to get the plugin to a stage where we can issue a release.

I have created an example application for testing. https://github.com/davidyell/Example-MuffinWebservice

@ADmad If you can think of anything else, or would like to do some testing yourself, please let me know if there are outstanding items and I will get them done.

I'm keen to get 2.0 released, so I can start working on the Pagination and Form Context

**Comment by ADmad** [comment]
I think we are ready to tag `dev` now. Do you want to give it a whirl with you test app and ensure everything is okay?

When merging `master` into `dev` I had to rename `AbstractDriver::getQueryLoggin()` to `AbstractDriver::isQueryLoggingEnabled()` as the latter method name has already been selected `1.4` to be similar to `Connection::isQueryLoggingEnabled()` in core.

**Comment by davidyell** [comment]
Seems to be working great for me, at least for read only web services.
