### ISSUE TITLE
Endpoint->getResourceClass() does not work correctly with custom Resource classes

### ISSUE THREAD

**Issue by Asgraf** [UseMuffin/Webservice#75]
If you try to create custom Resource subclass as shown [here:](https://github.com/UseMuffin/Webservice/tree/2.0.0-RC1#create-a-resource-optional) Endpoint->getResourceClass() method will always return null instead of class name. This will then cause Fatal Error here:
https://github.com/UseMuffin/Webservice/blob/2.0.0-RC1/src/Webservice/Webservice.php#L384

Tested on CakePHP 3.6.12 & Webservice 2.0.0-RC1

**Comment by davidyell** [comment]
Did you bootstrap the plugin to load the Factory?

**Comment by Asgraf** [comment]
> Did you bootstrap the plugin to load the Factory?
Yes, i did.
I have tested both on my existing app that worked correctly on Webservice 1.3 and on https://github.com/davidyell/Example-MuffinWebservice/ 

Try following steps:
1) clone and install https://github.com/davidyell/Example-MuffinWebservice/
(You will probably need to change required webservice version to 2.0.0-RC1 in composer.json)
2) create new file `/src/Model/Endpoint/BankHolidaysEndpoint.php` with following content:
```php
<?php
namespace App\Model\Resource;

use Muffin\Webservice\Model\Resource;
class BankHoliday extends Resource
{
}
```

You fill get Fatal Error: `Class name must be a valid object or a string`
at
`/vendor/muffin/webservice/src/Webservice/Webservice.php:328`

**Comment by davidyell** [comment]
Closing if favour of the open pull request #76
