### ISSUE TITLE
Edit object

### ISSUE THREAD

**Issue by r0kawa** [UseMuffin/Webservice#78]
I've error to match the edit object. Cake 3.6 try to find 

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.resources' doesn't exist`

This is the code under UsersWebservice

```
            $resource = $this->_transformResource(new UsersEndpoint(), $resultArray);
             return new ResultSet([$resource], 1);
```

and returning this object format

```
Muffin\Webservice\Model\Resource Object
(
    [id] => 3
    [username] => abc
    [fullname] => ABC
    [email] => xx@example.com
    [group_id] => 1
    [tenant_id] => 1
    [team_id] => 0
    [tenant] => stdClass Object
        (
            [id] => 1
            [code] => xxx
            [name] => xxx
            [active] => 1
            [created] => 2018-11-08T13:00:00
            [modified] => 2018-11-08T13:00:00
        )

    [group] => stdClass Object
        (
            [id] => 1
            [code] => SA
            [description] => Super Admin
            [tenant_id] => 0
        )

    [[new]] => 
```

Any suggestion

**Comment by davidyell** [comment]
I don't understand this issue. Please can you clarify.

What is happening?
What are you expecting to happen?

**Comment by r0kawa** [comment]
1. I'm using this using to create edit action for users form.

```
       if(!empty($query->where()['id'])) {

            $response = $this->driver()->client()->get('/users/' . $query->where()['id']);


            $resultArray = $response->body(function ($body) {
                $json = json_decode($body);
                return (array) $json->data;
               //return json_decode($body, true);
            });


            $resource = $this->_transformResource(new UsersEndpoint(), $resultArray);
             return new ResultSet([$resource], 1);
```
The return data is as the question above.

The code for UsersController.php 

```
       $this->loadModel('Users', 'Endpoint');
        $user =  $this->Users->find()->where(['id' => $id]);

        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->getData());

            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $this->set('user', $user->first());
```

there's an exception error from cake state

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'simdesk.resources' doesn't exist `


from the test file VERSION is 1.0.2 but i believe I'm using the dev-master from composer.json info

"muffin/webservice": "dev-master"

**Comment by ADmad** [comment]
Looks like like you haven't created a `User` resource class for the `UsersEndpoint`.

**Comment by r0kawa** [comment]
> u haven't created a `User` resource class for the `UsersEndpoint`.

Yes, i haven't. After I create it, it still output the same error. Do I need to include it somewhere in the webservice class or endpoint class ?

**Comment by davidyell** [comment]
https://github.com/UseMuffin/Webservice#use-it

**Comment by r0kawa** [comment]
> https://github.com/UseMuffin/Webservice#use-it

It's not like the data didn't return from the webservice. I've successfully query everything. But the problem

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'simdesk.resources' doesn't exist`

appear on the edit template page when I'm using below code

` <?= $this->Form->create($user) ?>`

I think the object that Form create expect is not the same as the web service return. When I'm commenting or remove $user variable , there's no error, but no data is fill inside the form. 

Below is the object that I sent to edit.ctp to create($user) . 

```
Muffin\Webservice\Model\Resource Object
(
    [id] => 3
    [username] => abc
    [fullname] => ABC
    [email] => xx@example.com
    [group_id] => 1
    [tenant_id] => 1
    [team_id] => 0
    [tenant] => stdClass Object
        (
            [id] => 1
            [code] => xxx
            [name] => xxx
            [active] => 1
            [created] => 2018-11-08T13:00:00
            [modified] => 2018-11-08T13:00:00
        )

    [group] => stdClass Object
        (
            [id] => 1
            [code] => SA
            [description] => Super Admin
            [tenant_id] => 0
        )

    [[new]] => 

```

**Comment by davidyell** [comment]
Yes, which is why you should create a UserResource class.

[Check out the source code](https://github.com/UseMuffin/Webservice/blob/master/src/Model/Resource.php#L9), the class extends Entity. So would be compatible with the `Form->create()`

**Comment by r0kawa** [comment]
actually I’ve create the userResource class after @ADmad comment above but the resource getting the same object . I’ve put at /src/Model/Resource/User.php

suppose the plugin getting it .

i’m only creating empty class like the example.

**Comment by r0kawa** [comment]
Ok, my bad. Put Users instead of User. I'm closing this one. Thank you for the guidance 💃

**Comment by r0kawa** [comment]
Sorry guys, need to reopen again.

`Argument 1 passed to Muffin\Webservice\Model\Endpoint::patchEntity() must be an instance of Cake\Datasource\EntityInterface, instance of Muffin\Webservice\Query given.`

The problem is when submitting the form for edit submission. Below is the code

```
public function edit($id = null)
    {

        $this->loadModel('Users', 'Endpoint');
       $user =  $this->Users->find()->where(['id' => $id]);

        if ($this->request->is(['patch', 'post', 'put'])) {

            $user = $this->Users->patchEntity($user, $this->request->getData());

            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
        $this->set('user', $user->first());
    }

```
I've tried to change it to $user->first(), no error 

` $user = $this->Users->patchEntity($user->first(), $this->request->getData());`

but different error

```
Missing schema User or webservice Users describe implementation
Muffin\Webservice\Exception\MissingEndpointSchemaException
```

any comment is appreciated. 

Thanks.

**Comment by ADmad** [comment]
It's pretty clear from the error message what the problem is. You need to pass an instance of `EntityInterface` aka `Resource` not `Query` to `patchEntity()`.

Change 
`$user =  $this->Users->find()->where(['id' => $id]);`  
to 
`$user =  $this->Users->find()->where(['id' => $id])->first();` 
or use `$user =  $this->Users->get($id);`.
