### ISSUE TITLE
Missing schema User or webservice Users describe implementation

### ISSUE THREAD

**Issue by r0kawa** [UseMuffin/Webservice#79]
I'm having this error once I tried to do the edit function. Should I define schema in some class ? 

```
Missing schema User or webservice Users describe implementation
Muffin\Webservice\Exception\MissingEndpointSchemaException
```

**Comment by EtienneBourque** [comment]
See this post: https://github.com/UseMuffin/Webservice/issues/77#issuecomment-446836512

The schema must be assigned in the initialize method of your Endpoint class.
