### ISSUE TITLE
Incorrect Namespace

### ISSUE THREAD

**Issue by steefaan** [UseMuffin/Webservice#8]
I crated the following driver:

```
namespace Gutscheinpony\Webservice\Driver;

use Cake\Network\Http\Client;
use Muffin\Webservice\AbstractDriver;

class Gutscheinpony extends AbstractDriver
{
    /**
     * {@inheritDoc}
     */
    public function initialize()
    {
        $this->client(new Client([
            'headers' => [
                'X-Api-Token' => $this->config('token')
            ]
        ]));

        $this->webservice('Offers');
    }
}
```

As error message I get:

```
Exception: Webservice class Gutscheinpony/Webservice.Offers (and fallback Gutscheinpony/Webservice.Gutscheinpony) could not be found. in [/var/www/schnaeppchenfuchs/vendor/muffin/webservice/src/AbstractDriver.php, line 218]
```

If I do it with: (probably it's more correct to specifiy the plugin here)

```
$this->webservice('Gutscheinpony.Offers');
```

I get:

```
Exception: Webservice class Gutscheinpony/Webservice.Gutscheinpony.Offers (and fallback Gutscheinpony/Webservice.Gutscheinpony) could not be found. in [/var/www/schnaeppchenfuchs/vendor/muffin/webservice/src/AbstractDriver.php, line 218]
```

It seems that the namespace building doesn't work properly here.

I think this https://github.com/UseMuffin/Webservice/blob/master/src/AbstractDriver.php#L95 needs to be `-1`, then it would work (but only for `$this->webservice('Offers');`) . I'm not sure here if this should be the error I will create a PR.

**Comment by Marlinc** [comment]
What exactly are you trying to do? Are you trying to use the ORM that's included? In that case you'll have to make a Webservice called `GutscheinponyWebservice`. Any endpoint that you use at that point will use the `GutscheinponyWebservice` to communicate with the remote service.

A example can be found at: https://github.com/cvo-technologies/cakephp-github/blob/3.0/src/Webservice/GitHubWebservice.php

**Comment by steefaan** [comment]
Thanks for your support. Issue solved.
