### ISSUE TITLE
Webservice twitter does not implement isQueryLoggingEnabled

### ISSUE THREAD

**Issue by dereuromark** [UseMuffin/Webservice#80]
Webservice twitter does not implement isQueryLoggingEnabled
Muffin\Webservice\Exception\UnimplementedWebserviceMethodException

vendor/cakephp/debug_kit/src/Panel/SqlLogPanel.php triggers this in the `if ($connection->isQueryLoggingEnabled()) {` call.
With CakePHP 3.7+

**Comment by dereuromark** [comment]
I didnt even notice that https://github.com/UseMuffin/Webservice/pull/81 has been opened and merged.
Sounds like we can close this then?

**Comment by ADmad** [comment]
I didn't reference this issue in the PR, so GH should have sent you a notification isn't it?
